### ISSUE TITLE
Add support for versionn 8.7.220.31

### ISSUE THREAD

**Issue by blksmr** [suleram/View8#11]
Hi please can you add compatibility for version 8.7.220.31

**Comment by K4ndoo** [comment]
Hey,
All you need is already here, you just need to build up the disassembler for this specific version (8.7.220.31)
you can check this repo if it helps
https://github.com/noelex/v8dasm

Very close to the version you are asking btw (8.7.220.25)

**Comment by blksmr** [comment]
> Hey, All you need is already here, you just need to build up the disassembler for this specific version (8.7.220.31) you can check this repo if it helps https://github.com/noelex/v8dasm
> 
> Very close to the version you are asking btw (8.7.220.25)

Ty for your help i succeeded in building v8dasm but the output format don't match for View8.
At least i guess it's the output format issue and i hope so.


`C:\Users\usr\Documents\GitHub\View8>py view8.py main.jsc output.js
Detecting version.
Detected version: 8.7.220.31.
Executing disassembler binary: C:\Users\usr\Documents\GitHub\View8\Bin\8.7.220.31.exe.
Disassembly completed successfully.
Parsing disassembled file.
Traceback (most recent call last):
  File "C:\Users\usr\Documents\GitHub\View8\view8.py", line 61, in <module>
    main()
  File "C:\Users\usr\Documents\GitHub\View8\view8.py", line 54, in main
    all_func = disassemble(args.input_file, args.disassembled, args.path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\view8.py", line 17, in disassemble
    return parse_disassembled_file(out_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\parse_v8cache.py", line 61, in parse_disassembled_file
    all_func = parse_file(out_name)
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usr\Documents\GitHub\View8\Parser\sfi_file_parser.py", line 182, in parse_file
    while next(lines) != "Start SharedFunctionInfo":
          ^^^^^^^^^^^
StopIteration`

I'm getting succesfull `disasm.tmp` and `isolate-0000032F00000000-16420-v8.log` files. Who looks fine i guess ?
Maybe i didn't understood something.
