### ISSUE TITLE
Long strings are truncated

### ISSUE THREAD

**Issue by th3spis** [suleram/View8#5]
Is there any chance to avoid truncating long strings? The patched V8 binary for disassembling is good, but it is not obtaining a string parameters since it is too long:

![Screenshot from 2024-09-16 17-35-51](https://github.com/user-attachments/assets/76b5d140-fa3e-4a84-8717-9be9ea12c2ce)

Therefore the decompiled code does not actually contain the real value of the string:

![Screenshot from 2024-09-16 17-39-15](https://github.com/user-attachments/assets/b09a2121-0094-4866-b56e-2665ad99b408)

**Comment by j4k0xb** [comment]
remove these lines: https://github.com/v8/v8/blob/0e75d85d8e3467a536bca01d89d8a180a8bcffca/src/objects/string.cc#L694-L699

```cpp
if (len > kMaxShortPrintLength) {
  accumulator->Add("...<truncated>>");
  accumulator->Add(SuffixForDebugPrint());
  accumulator->Put('>');
  return;
}
```
Also some unicode strings can't be parsed (ambiguous hex escapes, missing `>`, etc), needs a workaround

**Comment by th3spis** [comment]
Great, thank you!
