### ISSUE TITLE
Detected version: 15.37.333.192

### ISSUE THREAD

**Issue by heliocosta-dev** [suleram/View8#8]
Hey there,

I couldn't find any binary with this version. Could someone guide me with this?

Attaching the input file here just in case it can be useful in any way
[settings.zip](https://github.com/user-attachments/files/17267591/settings.zip)

Thanks in advance

**Comment by j4k0xb** [comment]
that's not a valid jsc file, most likely encrypted

**Comment by heliocosta-dev** [comment]
Appreciate the quick response.
